# name: Rust

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose

name: Build and Release

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      - name: Install Rust for macOS
        if: matrix.os == 'macos-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-apple-darwin
      - name: Install Rust for Windows
        if: matrix.os == 'windows-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install Rust for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-pc-windows-gnu

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install librust-gdk-dev gcc-mingw-w64-x86-64

      - name: Lint code
        run: just lint

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: just build-mac
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: just build-win
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: just build-linux

      - name: Upload build artefacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: out/nse*.zip
          if-no-files-found: error
  
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: sudo apt-get install librust-gdk-dev
      - name: Upload to Crates
        uses: actions-rs/cargo@v1
        with:
          command: publish

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./out
      - name: Create sha256sum for scoop
        run: sha256sum ./out/nse-windows-msvc.zip | cut -d ' ' -f 1 > ./out/nse-windows-msvc.zip.sha256
      # Remove the dots for the markdown header
      - name: MD Header
        run: echo "MD_HEADER=$(echo ${{ github.ref_name }} | sed 's/\.//g')" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./out/*
          name: nse ${{ github.ref_name }}
          body: |
            Compiled binaries for nse version `${{ github.ref_name }}` ([changelog](https://github.com/TechfaneTechnologies/nse/blob/main/CHANGELOG.md#${{ env.MD_HEADER }}))

            The provided binaries are for:

            - GNU Linux (x64 linux gnu)
            - macOS Apple Silicon (aarch64 darwin)
            - macOS Intel (x64 darwin)
            - GNU Windows, e.g. cygwin (x64 windows gnu)
            - MSVC Windows (x64 windows msvc)

            You can install these by downloading and unzipping the appropriate asset, and moving the executable to ~/bin or any other binary folder in your path.
